from enum import IntFlag

class FeedbackType(IntFlag):
    FEEDBACK_ENCODER_MEDIATED = 6
    FEEDBACK_NONE = 5
    FEEDBACK_EMF = 4
    FEEDBACK_ENCODER = 1

class FeedbackFlags(IntFlag):
    FEEDBACK_ENC_TYPE_BITS = 192
    FEEDBACK_ENC_TYPE_DIFFERENTIAL = 128
    FEEDBACK_ENC_TYPE_SINGLE_ENDED = 64
    FEEDBACK_ENC_REVERSE = 1
    FEEDBACK_ENC_TYPE_AUTO = 0

class HomeFlags(IntFlag):
    HOME_USE_FAST = 256
    HOME_STOP_SECOND_BITS = 192
    HOME_STOP_SECOND_LIM = 192
    HOME_STOP_SECOND_SYN = 128
    HOME_STOP_SECOND_REV = 64
    HOME_STOP_FIRST_BITS = 48
    HOME_STOP_FIRST_LIM = 48
    HOME_STOP_FIRST_SYN = 32
    HOME_STOP_FIRST_REV = 16
    HOME_HALF_MV = 8
    HOME_MV_SEC_EN = 4
    HOME_DIR_SECOND = 2
    HOME_DIR_FIRST = 1

class EngineFlags(IntFlag):
    ENGINE_LIMIT_RPM = 128
    ENGINE_LIMIT_CURR = 64
    ENGINE_LIMIT_VOLT = 32
    ENGINE_ACCEL_ON = 16
    ENGINE_ANTIPLAY = 8
    ENGINE_MAX_SPEED = 4
    ENGINE_CURRENT_AS_RMS = 2
    ENGINE_REVERSE = 1

class MicrostepMode(IntFlag):
    MICROSTEP_MODE_FRAC_256 = 9
    MICROSTEP_MODE_FRAC_128 = 8
    MICROSTEP_MODE_FRAC_64 = 7
    MICROSTEP_MODE_FRAC_32 = 6
    MICROSTEP_MODE_FRAC_16 = 5
    MICROSTEP_MODE_FRAC_8 = 4
    MICROSTEP_MODE_FRAC_4 = 3
    MICROSTEP_MODE_FRAC_2 = 2
    MICROSTEP_MODE_FULL = 1

class EngineType(IntFlag):
    ENGINE_TYPE_BRUSHLESS = 5
    ENGINE_TYPE_TEST = 4
    ENGINE_TYPE_STEP = 3
    ENGINE_TYPE_2DC = 2
    ENGINE_TYPE_DC = 1
    ENGINE_TYPE_NONE = 0

class DriverType(IntFlag):
    DRIVER_TYPE_EXTERNAL = 3
    DRIVER_TYPE_INTEGRATE = 2
    DRIVER_TYPE_DISCRETE_FET = 1

class PowerFlags(IntFlag):
    POWER_SMOOTH_CURRENT = 4
    POWER_OFF_ENABLED = 2
    POWER_REDUCT_ENABLED = 1

class Flags(IntFlag):
    ALARM_ENGINE_RESPONSE = 128
    ALARM_WINDING_MISMATCH = 64
    USB_BREAK_RECONNECT = 32
    ALARM_FLAGS_STICKING = 16
    ALARM_ON_BORDERS_SWAP_MISSET = 8
    H_BRIDGE_ALERT = 4
    LOW_UPWR_PROTECTION = 2
    ALARM_ON_DRIVER_OVERHEATING = 1

class BorderFlags(IntFlag):
    BORDERS_SWAP_MISSET_DETECTION = 8
    BORDER_STOP_RIGHT = 4
    BORDER_STOP_LEFT = 2
    BORDER_IS_ENCODER = 1

class EnderFlags(IntFlag):
    ENDER_SW2_ACTIVE_LOW = 4
    ENDER_SW1_ACTIVE_LOW = 2
    ENDER_SWAP = 1

class SyncInFlags(IntFlag):
    SYNCIN_GOTOPOSITION = 4
    SYNCIN_INVERT = 2
    SYNCIN_ENABLED = 1

class SyncOutFlags(IntFlag):
    SYNCOUT_ONPERIOD = 64
    SYNCOUT_ONSTOP = 32
    SYNCOUT_ONSTART = 16
    SYNCOUT_IN_STEPS = 8
    SYNCOUT_INVERT = 4
    SYNCOUT_STATE = 2
    SYNCOUT_ENABLED = 1

class EXTIOSetupFlags(IntFlag):
    EXTIO_SETUP_INVERT = 2
    EXTIO_SETUP_OUTPUT = 1

class EXTIOModeFlags(IntFlag):
    EXTIO_SETUP_MODE_OUT_BITS = 240
    EXTIO_SETUP_MODE_OUT_MOTOR_ON = 64
    EXTIO_SETUP_MODE_OUT_ALARM = 48
    EXTIO_SETUP_MODE_OUT_MOVING = 32
    EXTIO_SETUP_MODE_OUT_ON = 16
    EXTIO_SETUP_MODE_IN_BITS = 15
    EXTIO_SETUP_MODE_IN_ALARM = 5
    EXTIO_SETUP_MODE_IN_HOME = 4
    EXTIO_SETUP_MODE_IN_MOVR = 3
    EXTIO_SETUP_MODE_IN_PWOF = 2
    EXTIO_SETUP_MODE_IN_STOP = 1
    EXTIO_SETUP_MODE_IN_NOP = 0
    EXTIO_SETUP_MODE_OUT_OFF = 0

class BrakeFlags(IntFlag):
    BRAKE_ENG_PWROFF = 2
    BRAKE_ENABLED = 1

class ControlFlags(IntFlag):
    CONTROL_BTN_RIGHT_PUSHED_OPEN = 8
    CONTROL_BTN_LEFT_PUSHED_OPEN = 4
    CONTROL_MODE_BITS = 3
    CONTROL_MODE_LR = 2
    CONTROL_MODE_JOY = 1
    CONTROL_MODE_OFF = 0

class CtrlFlags(IntFlag):
    EEPROM_PRECEDENCE = 1

class CTPFlags(IntFlag):
    CTP_ERROR_CORRECTION = 16
    REV_SENS_INV = 8
    CTP_ALARM_ON_ERROR = 4
    CTP_BASE = 2
    CTP_ENABLED = 1

class UARTSetupFlags(IntFlag):
    UART_STOP_BIT = 8
    UART_PARITY_BIT_USE = 4
    UART_PARITY_BITS = 3
    UART_PARITY_BIT_MARK = 3
    UART_PARITY_BIT_SPACE = 2
    UART_PARITY_BIT_ODD = 1
    UART_PARITY_BIT_EVEN = 0

class BackEMFFlags(IntFlag):
    BACK_EMF_KM_AUTO = 4
    BACK_EMF_RESISTANCE_AUTO = 2
    BACK_EMF_INDUCTANCE_AUTO = 1

class MotorType(IntFlag):
    MOTOR_TYPE_BLDC = 3
    MOTOR_TYPE_DC = 2
    MOTOR_TYPE_STEP = 1
    MOTOR_TYPE_UNKNOWN = 0

class EncoderSettings(IntFlag):
    ENCSET_REVOLUTIONSENSOR_ACTIVE_HIGH = 256
    ENCSET_REVOLUTIONSENSOR_PRESENT = 64
    ENCSET_INDEXCHANNEL_PRESENT = 16
    ENCSET_PUSHPULL_OUTPUT = 4
    ENCSET_DIFFERENTIAL_OUTPUT = 1

class MBSettings(IntFlag):
    MB_POWERED_HOLD = 2
    MB_AVAILABLE = 1

class TSSettings(IntFlag):
    TS_AVAILABLE = 8
    TS_TYPE_BITS = 7
    TS_TYPE_SEMICONDUCTOR = 2
    TS_TYPE_THERMOCOUPLE = 1
    TS_TYPE_UNKNOWN = 0

class LimitSwitchesSettings(IntFlag):
    LS_SHORTED = 16
    LS_SW2_ACTIVE_LOW = 8
    LS_SW1_ACTIVE_LOW = 4
    LS_ON_SW2_AVAILABLE = 2
    LS_ON_SW1_AVAILABLE = 1